### ISSUE TITLE
Taking css Aspect 

### ISSUE THREAD

**Issue by Temi-Tade** [ANTAPEX/KINFLIP-WEBSITE#1]
Would like to take the css aspect for this, I would be doing the html for my css aspect

**Comment by ALIPHATICHYD** [comment]
Screenshot the part of the website you'd like to style

**Comment by Temi-Tade** [comment]
> Screenshot the part of the website you'd like to style

![IMG-20230302-WA0031](https://user-images.githubusercontent.com/100342148/222579117-b2f093ff-7835-451d-b6bf-01c702fc4c82.jpg)

**Comment by ALIPHATICHYD** [comment]
Niceee
