### ISSUE TITLE
the part of the project that i am taking

### ISSUE THREAD

**Issue by aderonmujudah** [ANTAPEX/KINFLIP-WEBSITE#13]
![WhatsApp Image 2023-03-05 at 23 56 05](https://user-images.githubusercontent.com/110620020/222990822-e0140572-8ecd-4c07-8303-92ffb9734622.jpeg)

**Comment by ALIPHATICHYD** [comment]
Oh nice you can start working on it now

**Comment by aderonmujudah** [comment]
Okay
