### ISSUE TITLE
Can I convert the code base to Reactjs

### ISSUE THREAD

**Issue by nueladeyemi1** [ANTAPEX/KINFLIP-WEBSITE#17]
Hello,
The project is currently written in HTML, CSS and JS.
Can I convert the current code base to ReactJs?

**Comment by ALIPHATICHYD** [comment]
unless you want to do it as a separate project 
This project is for people who are not familiar with react js yet but if you want a project with react js i can give you

**Comment by ALIPHATICHYD** [comment]
I have some react projects we can collaborate on
